# Generated by Django 2.0.8 on 2018-12-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, unique=True)),
                ('avatar', models.FileField(blank=True, default='{% static avatar.jpg%}', upload_to='')),
                ('bio', models.CharField(blank=True, max_length=400, verbose_name='About')),
                ('website', models.CharField(blank=True, max_length=5000)),
                ('phone', models.IntegerField()),
                ('country', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.User')),
            ],
        ),
    ]
